import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { createHash } from 'node:crypto';
import { Harness, delay, until } from '../scripts/harness';
test('real PTYs, Pixel guests, mouse windows and abrupt reconnect', { timeout: 40000 }, async () => {
  const h = new Harness();
  try {
    await h.ready();
    const shell = (await h.request({ type: 'launch', app: 'shell' })).id;
    const demo = (await h.request({ type: 'launch', app: 'demo' })).id;
    const second = (await h.request({ type: 'launch', app: 'demo' })).id;
    await until(async () => (await h.request({ type: 'inspect' })).metrics.frames >= 2);
    await h.attach();
    await h.request({ type: 'input', id: shell, event: { type: 'text', text: "export ZATARA_MARK=still_alive; printf '\\nREADY_%s\\n' \"$ZATARA_MARK\"\r" } });
    await until(async () => (await h.request({ type: 'screen', id: shell })).screen.rows.map((r: any[]) => r.map(c => c.text).join('')).join('\n').includes('READY_still_alive'));
    const before = (await h.request({ type: 'inspect' })).state;
    const w = before.windows.find((w: any) => w.id === second);
    h.save('.artifacts/before.png');
    await h.drag(w.x + 140, w.y + 18, 130, 80);
    const moved = (await h.request({ type: 'inspect' })).state.windows.find((w: any) => w.id === second);
    assert.ok(moved.x > w.x + 60, `drag x: ${w.x} → ${moved.x}`);
    const hash = (id: string) => createHash('sha256').update(fs.readFileSync(path.join(h.dir, 'test-frames', id + '.bgra'))).digest('hex');
    const previous = hash(second), other = hash(demo);
    await h.click(moved.x + 75, moved.y + 270);
    await until(() => hash(second) !== previous);
    assert.equal(hash(demo), other, 'clicks must not leak into an overlapping app');
    const clicked = hash(second);
    h.save('.artifacts/desktop.png');
    const pids = (await h.request({ type: 'inspect' })).state.windows.map((w: any) => w.pid);
    h.desktop!.kill('SIGKILL');
    await until(async () => !(await h.request({ type: 'inspect' })).state.attached);
    await h.attach();
    const after = (await h.request({ type: 'inspect' })).state;
    assert.deepEqual(after.windows.map((w: any) => w.pid), pids);
    assert.equal(hash(second), clicked, 'GUI state and rendered pixels survive attachment death');
    await h.request({ type: 'input', id: shell, event: { type: 'text', text: "printf '\\nRECONNECTED_%s\\n' \"$ZATARA_MARK\"\r" } });
    await delay(200);
    const screen = await h.request({ type: 'screen', id: shell });
    assert.ok(screen.screen.rows.map((r: any[]) => r.map(c => c.text).join('')).join('\n').includes('RECONNECTED_still_alive'));
    assert.ok(after.windows.every((w: any) => w.status === 'Running'));
    await h.drag(moved.x + moved.width - 3, moved.y + moved.height - 3, 50, 40);
    let current = (await h.request({ type: 'inspect' })).state.windows.find((w: any) => w.id === second);
    assert.ok(current.width > moved.width + 20, 'edge drag resizes the window');
    await h.click(current.x + 130, current.y + 18); await h.click(current.x + 130, current.y + 18);
    assert.equal((await h.request({ type: 'inspect' })).state.windows.find((w: any) => w.id === second).maximized, true);
    await h.click(130, 18); await h.click(130, 18);
    current = (await h.request({ type: 'inspect' })).state.windows.find((w: any) => w.id === second);
    assert.equal(current.maximized, false);
    // Open the title-bar menu, then choose Minimize using native pointer events.
    await h.click(current.x + 130, current.y + 18, 'right');
    await h.click(current.x + 165, Math.min(current.y + 18, h.height - 258) + 22);
    assert.equal((await h.request({ type: 'inspect' })).state.windows.find((w: any) => w.id === second).minimized, true);
    assert.equal((await h.request({ type: 'inspect' })).state.windows.find((w: any) => w.id === second).pid, moved.pid);
    await h.click(450, h.height - 30);
    assert.equal((await h.request({ type: 'inspect' })).state.windows.find((w: any) => w.id === second).minimized, false);
    await h.request({ type: 'input', id: shell, event: { type: 'text', text: "python3 -c 'for i in range(50000): print(i)'\r" } });
    await until(async () => (await h.request({ type: 'screen', id: shell })).screen.rows.map((r: any[]) => r.map(c => c.text).join('')).join('\n').includes('49999'));
    assert.ok((await h.request({ type: 'inspect' })).state.attached, 'sustained shell output must not disconnect the UI');
    const shellText = async (id: string) => (await h.request({ type: 'screen', id })).screen.rows.map((r: any[]) => r.map(c => c.text).join('')).join('\n');
    await h.request({ type: 'input', id: shell, event: { type: 'text', text: "printf '\\033[?1049hALT_SCREEN'\r" } });
    await until(async () => (await h.request({ type: 'screen', id: shell })).screen.alternate);
    await h.request({ type: 'input', id: shell, event: { type: 'text', text: "printf '\\033[?1049l'\r" } });
    await until(async () => !(await h.request({ type: 'screen', id: shell })).screen.alternate);
    const shell2 = (await h.request({ type: 'launch', app: 'shell' })).id;
    await h.request({ type: 'input', id: shell2, event: { type: 'text', text: "printf '\\nINDEPENDENT_%s_END\\n' \"${ZATARA_MARK-unset}\"\r" } });
    await until(async () => (await shellText(shell2)).includes('INDEPENDENT_unset_END'));
    const independent = (await h.request({ type: 'inspect' })).state.windows.filter((w: any) => w.kind === 'shell');
    assert.equal(new Set(independent.map((w: any) => w.pid)).size, 2);
    await h.request({ type: 'action', id: shell2, op: 'close' });
    await h.request({ type: 'action', id: second, op: 'close' });
    assert.equal((await h.request({ type: 'inspect' })).state.windows.length, 2);
  } finally { await h.close(); }
});
